"""Design-time interfaces for the Python backend; no provider is implemented."""
from typing import Any, Protocol

JsonObject = dict[str, Any]

class LearnerProfileReader(Protocol):
    async def read(self, user_id: str, version: int | None = None) -> JsonObject: ...

class TextGenerator(Protocol):
    async def generate(self, assignment: JsonObject, target: JsonObject) -> JsonObject: ...

class SemanticReviewer(Protocol):
    async def review(self, lesson: JsonObject, assignment: JsonObject) -> JsonObject: ...

class SpeechGenerator(Protocol):
    async def render(self, text: str, voice_version: str, idempotency_key: str) -> JsonObject: ...

class AudioInspector(Protocol):
    async def inspect(self, asset: JsonObject, expected_text: str, conditions: JsonObject) -> JsonObject: ...

class JobRepository(Protocol):
    async def create_once(self, user_id: str, key: str, request_hash: str, request: JsonObject) -> JsonObject: ...
    async def lease(self, worker_id: str, lease_seconds: int) -> JsonObject | None: ...
    async def advance(self, job_id: str, expected_row_version: int, stage: str, result: JsonObject) -> JsonObject: ...

class LessonRepository(Protocol):
    async def save_draft(self, lesson: JsonObject) -> None: ...
    async def publish_with_event(self, lesson: JsonObject, quality_reports: list[JsonObject]) -> None: ...
