from pathlib import Path
import json
P=Path(__file__).resolve().parent
D={key:json.loads((P/name).read_text()) for key,name in [('summary','review_summary.json'),('targets','target_review.json'),('relations','alignment_review.json'),('map','curriculum_map.json'),('source','source_calibration_audit.json'),('verification','verification.json')]}
h=r'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>长期课程地图 · 模型审核结果</title><style>*{box-sizing:border-box}body{margin:0;color:#263144;background:#f6f7fa;font:15px/1.65 system-ui,-apple-system,"PingFang SC",sans-serif}header,main{max-width:1200px;margin:auto;padding:26px}h1{font-size:25px;margin:0}h2{font-size:19px}p{margin:8px 0}.muted{font-size:13px;color:#68768a}.metrics{display:flex;gap:36px;flex-wrap:wrap;margin:20px 0}.metrics b{font-size:23px;display:block}.note{background:#fff4df;padding:12px 16px;color:#6c501b}.tabs,.filters{display:flex;flex-wrap:wrap;gap:8px;margin:18px 0}input,select,button{font:inherit;padding:8px 12px;border:1px solid #ced6e1;border-radius:5px;background:#fff;color:inherit}input{flex:1;min-width:200px}button{cursor:pointer}button.active{background:#184b8d;color:#fff}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #78a4df;outline-offset:2px}.box{background:#fff;border:1px solid #dce2eb;padding:20px;margin:14px 0;border-radius:5px}.badge{font-size:12px;padding:2px 7px;background:#edf1f6;display:inline-block;margin-right:5px}.ref{padding:12px 16px;border-left:3px solid #bdcfe9;background:#f6f8fb;margin:10px 0}.english{font-size:16px}details{margin:10px 0}summary{color:#184b8d;cursor:pointer}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.7 ui-monospace,monospace;max-height:420px;overflow:auto}table{width:100%;border-collapse:collapse;background:#fff}td,th{padding:12px;border-bottom:1px solid #dde3eb;text-align:left;vertical-align:top}a{color:#184b8d}.pager{display:flex;gap:12px;align-items:center;margin:18px 0}@media(max-width:600px){header,main{padding:18px}.metrics{gap:18px}}</style>
<header><h1>长期课程地图 · 模型审核结果</h1><p class="muted">1.0.1-model-reviewed · 2026-10-02 · 单一助手模型审核</p><div class="metrics"><div><b>424</b>目标已审核</div><div><b>24</b>目标改写</div><div><b>1,315</b>既有关系已判断</div><div><b>815</b>关系不采纳</div></div><p class="note">地图规格已完成模型辅助审核。当前版本仍需具体课程质检、实际大模型/语音评分测试及真实使用证据；本次审核不证明正式等级等价或学习效果。</p><p><a href="target_review.csv">下载审核表（Excel可打开）</a> · <a href="curriculum_map.json">新版后端地图</a> · <a href="README.md">接入规则</a> · <a href="verification.json">验证结果</a></p><nav class="tabs"><button data-tab="targets" class="active">逐目标审核</button><button data-tab="relations">标准对应决定</button><button data-tab="changes">修改前后</button><button data-tab="source">来源修复</button></nav></header><main><div class="filters"><input id="query" aria-label="搜索目标或对应" placeholder="搜索目标、编号或英文原文"><select id="level" aria-label="筛选阶段"></select><select id="filter" aria-label="筛选审核结果"></select></div><p id="count" class="muted"></p><div id="body"></div></main><script id="data" type="application/json">__DATA__</script><script>
const D=JSON.parse(document.getElementById('data').textContent),$=x=>document.getElementById(x),E=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),goals=new Map(D.map.learning_objectives.map(g=>[g.id,g])),names={retain_component_reference:'保留部分参考',reject_for_this_group:'不采纳：分组不匹配',reject_for_this_target:'不采纳：子目标未覆盖',reject_unreconciled_source:'不采纳：来源未对应'};let tab='targets',page=0;const size=20,badge=x=>`<span class="badge">${E(x)}</span>`,raw=x=>`<details><summary>完整审核字段</summary><pre>${E(JSON.stringify(x,null,2))}</pre></details>`;
function filters(){$('level').innerHTML='<option value="">全部阶段</option>'+D.map.levels.labels.map(x=>`<option>${E(x)}</option>`).join('');$('level').disabled=tab==='source'||tab==='relations';$('filter').innerHTML='<option value="">全部决定</option>'+(tab==='relations'?Object.entries(names).map(([v,t])=>`<option value="${v}">${t}</option>`).join(''):'<option value="changed">改写过的目标</option><option value="mapped">有采纳参考</option><option value="original">保留原创目标，无采纳参考</option>');$('filter').disabled=tab==='source'||tab==='changes'}
function render(){const q=$('query').value.trim().toLowerCase(),l=$('level').value,f=$('filter').value;let rows=tab==='relations'?D.relations:tab==='source'?D.source.changes:D.targets;
 rows=rows.filter(x=>(!q||JSON.stringify(x).toLowerCase().includes(q))&&(!l||tab==='relations'||tab==='source'||goals.get(x.objective_id).reference_stage===l)&&(tab!=='changes'||x.original_outcome!==x.reviewed_outcome)&&(tab==='relations'?(!f||x.decision===f):tab==='source'||tab==='changes'||!f||(f==='changed'&&x.original_outcome!==x.reviewed_outcome)||(f==='mapped'&&x.standard_references.length)||(f==='original'&&!x.standard_references.length)));
 if(page*size>=rows.length)page=0;let selected=rows.slice(page*size,(page+1)*size);$('count').textContent=`符合筛选：${rows.length} 条`;
 if(tab==='targets'){$('body').innerHTML=selected.map(r=>`<article class="box"><h2>${E(r.reviewed_outcome)}</h2>${badge(goals.get(r.objective_id).reference_stage)}${badge(r.original_outcome!==r.reviewed_outcome?'已改写':'保留目标')}${badge(r.standard_references.length?'部分标准参考':'原创目标')}<p class="muted">${E(r.objective_id)}</p>${r.original_outcome!==r.reviewed_outcome?`<p>修改前：${E(r.original_outcome)}</p>`:''}<p>审核理由：${E(r.clarity_reason)}</p><p>任务须提供：${E(r.task_conditions.required_facts)}</p><p>判断边界：${E(r.task_conditions.success_boundary)}</p><details><summary>如何判断完成与不可判定</summary>${Object.entries(r.assessment_check).map(([k,v])=>`<p><b>${({pass:'完成',partial:'部分完成',fail:'未完成',unjudgeable:'不可判定'})[k]}：</b>${E(v)}</p>`).join('')}</details><h3>已采纳的 GSE 参考</h3>${r.standard_references.map(s=>`<div class="ref">${badge('GSE '+s.gse)}${badge(s.skill)}${badge(s.outside_reference_stage?'跨阶段，仅资源/进阶参考':'本阶段设计参考')}<p class="english">${E(s.outcome_en)}</p><p class="muted">${E(s.limits)}</p><a href="${E(s.source_file)}#page=${s.pdf_page}" target="_blank" rel="noopener">来源 PDF · 第 ${s.pdf_page} 页</a></div>`).join('')||'<p class="muted">当前没有采纳的对应。可按原创目标设计课程，不给它伪造标准分数。</p>'}<details><summary>CLB 条件与发布规则</summary><p>仅作条件参考，非节点或学习者等级等价。</p><p>${r.clb_review.source_ids.map(E).join('；')}</p><p>需要补齐：${r.task_conditions.must_materialize_before_use.map(E).join('；')}</p><p>${E(r.stage_review)}</p></details>${raw(r)}</article>`).join('')}
 else if(tab==='relations'){$('body').innerHTML=selected.map(r=>`<article class="box">${badge(names[r.decision])}${badge(r.scope==='group'?'能力分组':'具体目标')}<h2>${E(r.target)}</h2><p class="muted">${E(r.objective_id||r.node_id)} → ${E(r.reference_id)}</p><p class="english">${E(r.source_text||'旧条目来源未匹配')}</p><p>${E(r.reason)}</p>${raw(r)}</article>`).join('')}
 else {$('body').innerHTML=(tab==='source'?`<p>剔除页边 PRO/AC 标签并核对旧ID别名：4,054条源记录，167条旧记录的技能/分数修正。仍有8个旧ID未对应并隔离。听说目标去重后1,151条。</p>`:'')+`<div style="overflow:auto"><table><thead><tr><th>编号 / 原文</th><th>修改前</th><th>修改后</th></tr></thead><tbody>${selected.map(r=>tab==='changes'?`<tr><td>${E(r.objective_id)}</td><td>${E(r.original_outcome)}</td><td>${E(r.reviewed_outcome)}<p class="muted">${E(r.clarity_reason)}</p></td></tr>`:`<tr><td>${E(r.id)}<p>${E(r.text)}</p></td><td>${E(r.before.skill)} · GSE ${r.before.gse}</td><td>${E(r.after.skill)} · GSE ${r.after.gse}</td></tr>`).join('')}</tbody></table></div>`}
 if(!rows.length)$('body').innerHTML='<p>当前筛选无匹配，请调整筛选条件。</p>';
 else{$('body').insertAdjacentHTML('beforeend',`<div class="pager"><button id="prev" ${page===0?'disabled':''}>上一页</button><span>第 ${page+1} / ${Math.ceil(rows.length/size)} 页</span><button id="next" ${(page+1)*size>=rows.length?'disabled':''}>下一页</button></div>`);$('prev').onclick=()=>{page--;render()};$('next').onclick=()=>{page++;render()}}
}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;page=0;$('query').value='';document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));filters();render()});let timer;$('query').oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{page=0;render()},150)};$('level').onchange=$('filter').onchange=()=>{page=0;render()};filters();render();
</script></html>'''
(P/'report.html').write_text(h.replace('__DATA__',json.dumps(D,ensure_ascii=False,separators=(',',':')).replace('<','\\u003c')))
print(str(P/'report.html'))
